### ISSUE TITLE
Direct use of FFN

### ISSUE THREAD

**Issue by jackyko1991** [WenChentao/3DeeCellTracker#6]
Hi I have completed segmentation using third party segmentation tools.

I am trying to load the pre-trained FFN to perform cell tracking. Any instruction to by-pass UNet part and perhaps retrain the FFN to optimize tracking performance?

**Comment by WenChentao** [comment]
@jackyko1991 
Because the training program has not yet been integrated into the 3DeeCellTracker package, retraining is not possible. If you want to train your own FFN, you can look at the following codes, which are still in development: https://github.com/WenChentao/3DeeCellTracker/blob/backend_pytorch/CellTracker/ffn.py
https://github.com/WenChentao/3DeeCellTracker/blob/backend_pytorch/Examples/Train_old_ffn.ipynb

**Comment by WenChentao** [comment]
Here is a related question #10 Please see the updated response there.

In addition, the latest version 0.5.2-alpha allows you to train a custom FFN with custom data.
